import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateReport = (analysis) => {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();

  // ===========================
  // Header
  // ===========================
  doc.setFillColor(33, 150, 243);
  doc.rect(0, 0, pageWidth, 20, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("PCB ANALYSIS REPORT", pageWidth / 2, 13, {
    align: "center",
  });

  doc.setTextColor(0, 0, 0);

  let y = 30;

  // Date
  doc.setFontSize(11);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, y);

  y += 12;

  // ===========================
  // PCB Summary
  // ===========================
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("PCB Summary", 14, y);

  y += 8;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  doc.text(`PCB Type : ${analysis.pcbType}`, 16, y);

  y += 8;

  doc.text(`Confidence : ${analysis.confidence}`, 16, y);

  y += 12;

  // ===========================
  // Components Table
  // ===========================
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Detected Components", 14, y);

  y += 6;

  autoTable(doc, {
    startY: y,
    head: [["Designator", "Type", "Value / Part"]],
    body: analysis.components.map((c) => [
      c.designator || "-",
      c.type || "-",
      c.partNumber ||
        c.value ||
        c.marking ||
        "-"
    ]),
    styles: {
      fontSize: 10,
    },
    headStyles: {
      fillColor: [33, 150, 243],
    },
  });

  y = doc.lastAutoTable.finalY + 12;

  // ===========================
  // Suggestions
  // ===========================
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("AI Suggestions", 14, y);

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  if (analysis.suggestions.length === 0) {
    doc.text("No suggestions.", 18, y);
    y += 8;
  } else {
    analysis.suggestions.forEach((item) => {
      const lines = doc.splitTextToSize("• " + item, 170);
      doc.text(lines, 18, y);
      y += lines.length * 6;
    });
  }

  y += 8;

  // ===========================
  // Missing Components
  // ===========================
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Missing Components", 14, y);

  y += 8;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  if (analysis.missingComponents.length === 0) {
    doc.text("No missing components detected.", 18, y);
    y += 8;
  } else {
    analysis.missingComponents.forEach((item) => {
      doc.text("• " + item, 18, y);
      y += 6;
    });
  }

  y += 8;

  // ===========================
  // Faults
  // ===========================
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Fault Detection", 14, y);

  y += 8;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  if (analysis.faults.length === 0) {
    doc.text("No visible faults detected.", 18, y);
    y += 8;
  } else {
    analysis.faults.forEach((item) => {
      doc.text("• " + item, 18, y);
      y += 6;
    });
  }

  // ===========================
  // Footer
  // ===========================
  doc.setFontSize(10);

  doc.setTextColor(120);

  doc.text(
    "Generated by PCB Analyzer",
    pageWidth / 2,
    287,
    {
      align: "center",
    }
  );

  doc.save("PCB_Analysis_Report.pdf");
};